### PR TITLE
Added .gitignore, trust me it's good for you

### PR DESCRIPTION
**Pull request by assafnativ**

### CODE REVIEW

**Comment by sylveon** [comment]
Most of that .gitignore is useless for a non-Python project.

Excluding only `.exe`, `.dll`, `.obj`  and `.pdb` would have the same effect.

**Comment by AraHaan** [comment]
@sylveon I would also add ``.vs``, *.ipdb, *.ipch, *.iobj. <auto generated manifest xml file>, Debug, Release, all the other configuration/platform mixes.

**Comment by assafnativ** [comment]
Ok, I've removed the Python stuff

**Comment by AraHaan** [comment]
You forgot the A there in that commit message.

**Pull request merged**
