### PR TITLE
Move repetitive content to detours.h under #ifdef DETOURS_INTERNAL.

### PR DESCRIPTION
**Pull request by jaykrell**

### CODE REVIEW

**Comment by dtarditi** [comment]
This change looks fine, other than the DETOURS_INTERNAL #ifdef being at the top of Detours.h.     It could confuse people reading the header file to see this as the first thing.  Could you move the code lower in Detours.h, where other DETOURS_INTERNAL code is located.

**Comment by jaykrell** [comment]
Just move into the existing slightly later DETOURS_INTERNAL block? Yes that looks like it will work.

**Comment by dtarditi** [comment]
Yes, just moving it slightly later would be great.

**Comment by jaykrell** [comment]
If you move it down just one "section" you get:

z:\s\detours\src\detours.h(47) : fatal error C1189: #error :  Unknown architecture (x86, amd64, ia64, arm, arm64)
modules.cpp

because _X86_ etc. are defined by windows.h.

I probably put this right at the top, because everyone else was doing it before including detours.h.

**Comment by jaykrell** [comment]
Prefer repetition and prettier detours.h? Or just delayed?

**Comment by dtarditi** [comment]
Could we leave the #include "windows.h" in the .c files, and the move the code down in Detours.h?   Or does  the #define _ARM_WINAPI_PARTITION_DESKTOP_SDK_AVAILABLE need to precede the include of "windows.h"?

**Comment by jaykrell** [comment]
I think what you hint at is true -- _ARM_WINAPI_PARTITION_DESKTOP_SDK_AVAILABLE must be early. At least in the past. ARM development was by default limited to "the store", unless explicitly enable "desktop" development.
Oh, um, another option is /D_ARM_WINAPI_PARTITION_DESKTOP_SDK_AVAILABLE in Makefile. I like source to be more build-system-independent though.

**Pull request merged**
