### PR TITLE
Allow compilation with MinGW to succeed

### PR DESCRIPTION
**Pull request by virtuald**
What the title says. MinGW doesn't support `__try` and `__except`, so it's just defined out here as it doesn't seem there's a better way to handle it.

Note: Includes #107

### CODE REVIEW

**Comment by bgianfo** [comment]
Without SEH support, it's not safe to execute the code that is currently guarded by __try / __except.
You'll crash at runtime, you should be able to easily verify this by running any of the tests, they will most likely crash instantly.

I'm not sure it makes sense to even support detours being built and run in this configuration.

**Comment by bgianfo** [comment]
Also, it looks like the changes from #107 where mistakenly included here as well.

**Comment by Thaodan** [comment]
How did you compile it with mingw, by hand or using different makefiles?

**Comment by virtuald** [comment]
Using different makefiles. I used cmake, very simple.

**Comment by bgianfo** [comment]
Merging this as it appears harmless and enables this corner case scenario. 
Thanks @virtuald sorry for the delay!

**Pull request merged**
