### PR TITLE
Replace confusing x86/amd64 disassembly table with reasonable logic.

### PR DESCRIPTION
**Pull request by jaykrell**

### CODE REVIEW

**Comment by jaykrell** [comment]
ping?

**Comment by dtarditi** [comment]
Hi Jay,

This change looks reasonable.  I agree it is an improvement over the table, which is pretty confusing compared to the manual.   Could you comment on the testing of this change that you've done?  This is core code and any mistake here could cause significant problems.

Thanks,
Dave

**Comment by jaykrell** [comment]
Agreed it is a bit scary. I can try to revisit/retest. Maybe leave the code available for testing purposes.

**Comment by jaykrell** [comment]
Indeed there was a mistake for 32bit x86.
The testing/testability is much better now, but might want to throw more sequences at it still.

**Comment by jaykrell** [comment]
GitHub does not show the diff properly. Even though I did not change whitespace, you have to go to diff settings and hide whitespace, in order for it to render the old path w/o change.

**Comment by jaykrell** [comment]
Proved too "sensitive" or just delayed?

**Comment by jaykrell** [comment]
Or the testing is too ugly? Or inadequate? Or other?

**Comment by dtarditi** [comment]
@jaykrell,  thanks for making these changes and testing this further.  I'm glad to see that we have higher confidence in this code and that you find an issue in it using the testing.

You mentioned throwing more sequences at this.  I'm not sure how to do that.  As you know, Detours started as a research project.   The only tests that we have are the samples, which are run manually.   Any ideas?

**Comment by dtarditi** [comment]
@jaykrell, any thoughts on further testing of this change?

**Comment by dtarditi** [comment]
Closing - there have been no further suggestions on how to ensure this is well tested.

**Comment by jaykrell** [comment]
Oh darn. There are tests, I’ll look around.
Some used internal msdis though. :(

**Pull request closed without merging**
